import Link from 'next/link';
import { db } from '@/lib/db';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

const reports = [
  { label: 'Monthly Report', href: '/api/reports?type=monthly&format=pdf' },
  { label: 'Partner Report', href: '/api/reports?type=partner&format=pdf' },
  { label: 'Card Report', href: '/api/reports?type=card&format=excel' },
  { label: 'Vendor Report', href: '/api/reports?type=vendor&format=csv' },
  { label: 'Tax Report', href: '/api/reports?type=tax&format=pdf' },
  { label: 'Annual Report', href: '/api/reports?type=annual&format=excel' }
];

export default async function ReportsPage() {
  const generated = await db.report.findMany({ orderBy: { createdAt: 'desc' }, take: 10, include: { generatedBy: true } });

  return (
    <div className="space-y-8">
      <Card>
        <CardHeader>
          <CardTitle>Report Builder</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {reports.map((report) => (
            <Link key={report.label} href={report.href} className="rounded-3xl border border-ink-200 bg-white p-4 transition hover:border-gold-300 hover:shadow-lg dark:border-ink-800 dark:bg-ink-900">
              <div className="font-semibold">{report.label}</div>
              <div className="mt-2 text-sm text-ink-500">Export professional branded PDF, Excel, or CSV outputs.</div>
            </Link>
          ))}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Recent Reports</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {generated.map((report) => (
            <div key={report.id} className="flex items-center justify-between rounded-2xl border border-ink-200 px-4 py-3 dark:border-ink-800">
              <div>
                <div className="font-semibold">{report.type} · {report.format}</div>
                <div className="text-xs text-ink-500">Generated by {report.generatedBy.name}</div>
              </div>
              <Link
                href={report.fileUrl ?? '#'}
                className="rounded-full border border-ink-200 px-4 py-2 text-sm font-semibold text-ink-900 transition hover:border-gold-300 hover:bg-gold-50 dark:border-ink-800 dark:text-white dark:hover:bg-ink-800"
              >
                Open
              </Link>
            </div>
          ))}
        </CardContent>
      </Card>
    </div>
  );
}
